2020-07-22 10:43:06,961 ERROR 36372 nodejs.ClusterClientNoResponseError: client no response in 2947965ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/yqg/personal/projects/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 36372
hostname: yqgdeMBP-10.lan

2020-07-22 19:04:47,900 ERROR 36372 nodejs.ClusterClientNoResponseError: client no response in 2273927ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/yqg/personal/projects/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 36372
hostname: yqgdeMBP-10.lan

2020-07-22 19:42:50,180 ERROR 36372 nodejs.ClusterClientNoResponseError: client no response in 2260794ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/yqg/personal/projects/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 36372
hostname: yqgdeMBP-10.lan

2020-07-23 02:08:48,787 ERROR 36372 nodejs.ClusterClientNoResponseError: client no response in 14417697ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/yqg/personal/projects/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 36372
hostname: yqgdeMBP-10.lan

2020-07-23 04:09:02,181 ERROR 36372 nodejs.ClusterClientNoResponseError: client no response in 7213230ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/yqg/personal/projects/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 36372
hostname: yqgdeMBP-10.lan

2020-07-23 06:09:23,071 ERROR 36372 nodejs.ClusterClientNoResponseError: client no response in 7220314ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/yqg/personal/projects/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 36372
hostname: yqgdeMBP-10.lan

2020-07-23 06:22:45,009 ERROR 36372 nodejs.ClusterClientNoResponseError: client no response in 801439ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/yqg/personal/projects/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 36372
hostname: yqgdeMBP-10.lan

2020-07-23 07:16:06,150 ERROR 36372 nodejs.ClusterClientNoResponseError: client no response in 3178749ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/yqg/personal/projects/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 36372
hostname: yqgdeMBP-10.lan

2020-07-23 08:26:05,772 ERROR 36372 nodejs.ClusterClientNoResponseError: client no response in 3858241ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/yqg/personal/projects/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 36372
hostname: yqgdeMBP-10.lan

2020-07-23 10:42:26,830 ERROR 36372 nodejs.ClusterClientNoResponseError: client no response in 3699610ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/yqg/personal/projects/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 36372
hostname: yqgdeMBP-10.lan

